using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SCRIPTERS.BLL;
using SCRIPTERS.Core.Models;
using SCRIPTERS.Models;

namespace SCRIPTERS.Controllers
{
    [Authorize(Roles = "Manager")]
    public class ExpenseItemsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        Common common = new Common();
        ExpenseItemBll expenseItemBll = new ExpenseItemBll();
        bool status = false;

        #region AutoGeneratedCode

        /*
         *  // GET: ExpenseItems
        public ActionResult Index()
        {
            var expenseItems = db.ExpenseItems.Include(e => e.ExpenseCategory);
            return View(expenseItems.ToList());
        }

        // GET: ExpenseItems/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ExpenseItem expenseItem = db.ExpenseItems.Find(id);
            if (expenseItem == null)
            {
                return HttpNotFound();
            }
            return View(expenseItem);
        }

        // GET: ExpenseItems/Create
        public ActionResult Create()
        {
            ViewBag.ExpenseCategoryId = new SelectList(db.ExpenseCategories, "Id", "Name");
            return View();
        }

        // POST: ExpenseItems/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Code,Description,Image,ExpenseCategoryId")] ExpenseItem expenseItem)
        {
            if (ModelState.IsValid)
            {
                db.ExpenseItems.Add(expenseItem);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ExpenseCategoryId = new SelectList(db.ExpenseCategories, "Id", "Name", expenseItem.ExpenseCategoryId);
            return View(expenseItem);
        }

        // GET: ExpenseItems/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ExpenseItem expenseItem = db.ExpenseItems.Find(id);
            if (expenseItem == null)
            {
                return HttpNotFound();
            }
            ViewBag.ExpenseCategoryId = new SelectList(db.ExpenseCategories, "Id", "Name", expenseItem.ExpenseCategoryId);
            return View(expenseItem);
        }

        // POST: ExpenseItems/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Code,Description,Image,ExpenseCategoryId")] ExpenseItem expenseItem)
        {
            if (ModelState.IsValid)
            {
                db.Entry(expenseItem).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ExpenseCategoryId = new SelectList(db.ExpenseCategories, "Id", "Name", expenseItem.ExpenseCategoryId);
            return View(expenseItem);
        }

        // GET: ExpenseItems/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ExpenseItem expenseItem = db.ExpenseItems.Find(id);
            if (expenseItem == null)
            {
                return HttpNotFound();
            }
            return View(expenseItem);
        }

        // POST: ExpenseItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ExpenseItem expenseItem = db.ExpenseItems.Find(id);
            db.ExpenseItems.Remove(expenseItem);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
         */

        #endregion


        public ActionResult List()
        {
            List<ExpenseItem> expenseItems = expenseItemBll.List();
            return View(expenseItems);
        }

        // GET: Items/Details/5
        //public ActionResult Details(int id)
        //{
        //    return View();
        //}

        // GET: Items/Create

        public ActionResult Create()
        {
            ViewBag.autoCode = expenseItemBll.GenerateAutoCode();
            ViewBag.ExpenseCategoryId = expenseItemBll.GetExpenseItemCategory();
            return View();
        }

        // POST: Items/Create
        [HttpPost]
        public ActionResult Create(ExpenseItem expenseItem, HttpPostedFileBase ImageFile)
        {
            if (ImageFile == null)
            {
                ModelState.AddModelError("Image", "Please upload an Image");
            }
            bool isValidFormate = common.ImageValidation(ImageFile);
            if (isValidFormate == false)
            {
                ModelState.AddModelError("Image", "only png,jpg,jpeg format is allowed");
            }

            byte[] convertedImage = common.ConvertImage(ImageFile);
            expenseItem.Image = convertedImage;
            if (ModelState.IsValid)
            {
                status = expenseItemBll.Create(expenseItem);
                if (status == true)
                {
                    return RedirectToAction("List", "ExpenseItems");
                }
                else
                {
                    ViewBag.Message = "Expense Catagory added failed";
                }
            }
            ViewBag.ExpenseCategoryId = expenseItemBll.GetExpenseItemCategory();
            return View(expenseItem);

        }

        // GET: Items/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Error", "Home");
            }
            ExpenseItem expenseItem = expenseItemBll.GetById(id);
            if (expenseItem == null)
            {
                return RedirectToAction("Error", "Home");
            }
            ViewBag.ExpenseCategoryId = expenseItemBll.GetExpenseItemCategory();
            return View(expenseItem);
        }

        // POST: Items/Edit/5
        [HttpPost]
        public ActionResult Edit(ExpenseItem expenseItem, HttpPostedFileBase ImageFile)
        {
            if (ImageFile != null)
            {
                bool isValidFormate = common.ImageValidation(ImageFile);
                if (isValidFormate == false)
                {
                    ModelState.AddModelError("Image", "only png,jpeg,jpg formates are allowed");
                }
                byte[] convertedImage = common.ConvertImage(ImageFile);
                expenseItem.Image = convertedImage;
            }

            if (ModelState.IsValid)
            {
                status = expenseItemBll.Edit(expenseItem);
                if (status == true)
                {
                    return RedirectToAction("List", "ExpenseItems");
                }
                else
                {
                    ViewBag.Message = "Item is not updated succesfully";
                }
            }

            ViewBag.ExpenseCategoryId = expenseItemBll.GetExpenseItemCategory();
            return View(expenseItem);

        }

        // GET: Items/Delete/5
        public JsonResult Delete(int id)
        {
            status = expenseItemBll.Delete(id);
            if (status == true)
            {
                return Json(1);
            }
            return Json(0);
        }

        // POST: Items/Delete/5
        //[HttpPost]
        //public ActionResult Delete(int id, FormCollection collection)
        //{
        //    try
        //    {
        //        // TODO: Add delete logic here

        //        return RedirectToAction("Index");
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}



        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}
